### ISSUE TITLE
Minor cosmetic issues

### ISSUE THREAD

**Issue by aroberge** [kartik-karz/subtlegold-obsidian#3]
When viewing the settings, some items are hard to see as the text is white on "subtlegold".
![image](https://user-images.githubusercontent.com/629698/93601489-ad3c2780-f997-11ea-8366-d0b71219fad4.png)
![image](https://user-images.githubusercontent.com/629698/93601507-b3320880-f997-11ea-8123-eb99a21dd7e5.png)

I appended the following in my local version of the css file
```css
/* Check for update and similar button when viewing the settings */
button.mod-cta {
    color: var(--interactive-normal);
    background-color: (--interactive-accent)
}

/* Notice when fetching community themes */
div.notice {
    color: var(--interactive-normal) !important;
    background-color: (--interactive-accent)
}
```
Here's the result.
![image](https://user-images.githubusercontent.com/629698/93601623-d9f03f00-f997-11ea-9e0c-604dbbc9f95d.png)
![image](https://user-images.githubusercontent.com/629698/93601639-deb4f300-f997-11ea-9fd3-f14a89ef92f9.png)

Again, I'm not suggesting that these are the best possible choices, and they are only suggestions, but I do find the increased contrast useful.
